FROM keycloak/keycloak:22.0.1
HEALTHCHECK --interval=30s --start-period=15s --timeout=10m --retries=10 CMD bash -c 'echo -n > /dev/tcp/127.0.0.1/8080'
COPY ./src/main/resources/ClientFhirServerRealm.json /opt/keycloak/data/import/ClientFhirServerRealm.json