name: Automated Tests CI

on:
  pull_request:
    branches: [ master ]

jobs:
  automated-tests-ci: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt-openj9'
      
    - name: Test Server against automated tests
      run: gradle clean check