name: Automated Tests CI

on:
  pull_request:
    branches: [ master ]

jobs:
  automated-tests-ci: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Test Server against automated tests
      run: ./gradlew clean check